# -*- coding: utf-8 -*-
"""dict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfzVM5aroTkuAUDorNeCTkQzwFOLEHLy
"""

tarifa = [("onibus", "SP", 10),
          ("onibus", "RJ", 9),
          ("onibus", "ZZ", 5),
          ("taxi", "RJ", 15),
          ("taxi", "AL", 50),
          ("taxi", "SP", 20),
          ("taxi", "ZZ", 30)]

tarifa

transporte = input("Digite o transporte: ")
estado = input("Digite o estado: ")

for item in tarifa:
  if item[0] == transporte:
    if item[1] == estado:
      print(item[1], item[2])
      break
    else:
      if item[1] == "ZZ":
        print(estado, item[2], item[1])

conta = 0
for item in tarifa:
  if item[0] == "taxi":
    print(conta, item[1], item[2])
  conta += 1
print(conta)

#DICT

tarifa_dict = {"onibus": {'RJ': 9,
                          'SP': 10,
                          'ZZ': 5},
               "taxi": {'RJ': 15,
                        'SP': 20,
                        'AL': 50,
                        'ZZ': 30}}
tarifa_dict

for tarifa in tarifa_dict.keys():
  for i in tarifa_dict[tarifa].keys():
    print(tarifa_dict[tarifa][i])

transporte = input("Digite o transporte: ")
estado = input("Digite o estado: ")

if tarifa_dict.get(transporte):
  if tarifa_dict[transporte].get(estado):
    print(tarifa_dict[transporte][estado])
  else:
    print(tarifa_dict[transporte]['ZZ'])

tarifa_dict['onibus'].get('RJ', 'erro')

dados_pessoais = {
    "Silva": {
        "Joao": {"idade": 20, "cidade": "São Paulo"},
        "Ana": {"idade": 21, "cidade": "Botucatu", "filho": "maria"}
    },
    "Souza": {
        "Maria": {"idade": 35, "cidade": "Campinas"},
        "Otavio": {"idade": 44, "cidade": "Campinas", "filho": {"maria": 10,
                                                                "joao": 5}}
    },
    "Oliveira": {
        "Jose": {"idade": 56, "cidade": "Santos"},
        "Caio": {"idade": 80, "cidade": "Santos"}
    }
}

sobrenome = 'Souza'
for i in dados_pessoais[sobrenome].keys():
  for j in dados_pessoais[sobrenome][i].keys():
    if not type(dados_pessoais[sobrenome][i][j]) == dict:
      print(i, j, dados_pessoais[sobrenome][i][j])
    else:
      for k in dados_pessoais[sobrenome][i][j].keys():
        print(i, j, k, dados_pessoais[sobrenome][i][j][k])



