# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsC53VVTgXHsFFuNDSz2m4Opz5SDzBrJ
"""

a = 10

print(a)

print(type(a))

print(type(a))





